spring:
  application:
    name: resume-backend
  datasource:
    url: jdbc:mysql://db:3306/resume_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.label2775.resume: INFO

